fixtures:
  repositories:
    'keystone'  : 'git://github.com/stackforge/puppet-keystone'
    'nova'      : 'git://github.com/stackforge/puppet-nova'
    'openstack' : 'git://github.com/stackforge/puppet-openstack'
    'firewall'  : 'git://github.com/puppetlabs/puppetlabs-firewall'
    'haproxy'   : 'git://github.com/puppetlabs/puppetlabs-haproxy'
    'puppet'    : 'git://github.com/puppetlabs/puppetlabs-puppet'
    'puppetdb'  : 'git://github.com/puppetlabs/puppetlabs-puppetdb'
    'apache'    : 'git://github.com/puppetlabs/puppetlabs-apache'
    'apt'       : 'git://github.com/puppetlabs/puppetlabs-apt'
    'stdlib'    : 'git://github.com/puppetlabs/puppetlabs-stdlib'
    'inifile'   : 'git://github.com/puppetlabs/puppetlabs-inifile'
    'keepalived': 'git://github.com/arioch/puppet-keepalived'
    'sysctl'    : 'git://github.com/thias/puppet-sysctl'
  symlinks:
    'openstacklib' : "#{source_dir}"
